apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: port1
      targetPort: 5672
    - port: 15672
      name: port2
      targetPort: 15672
  type: LoadBalancer